import React, { useEffect, useState, useCallback } from 'react';
import { putSharedItem, getSharedItem, listSharedItems, StorageError } from '../lib/storage';
import { LOOK_OPTIONS, LOOK_MAP } from './lookOptions';
import { useTheme } from './ThemeContext';
import { AccessCodeManager } from './AccessGate';
import { DeadlineManager, CsvExporter } from './AdminTools';
import { Confetti } from './Confetti';
import { ShareWinnerButton } from './ShareWhatsApp';
const TABLE='baby-bets';const AT='prode-admin';const AK='real-birth-data';const APK='admin-password';const DP='alanna2026';
interface Bet{nickname:string;date:string;time:string;weight?:number|null;length?:number|null;look?:string|null;message:string;timestamp:number;}
interface RD{date:string;time:string;weight:number;length:number;look:string;revealed:boolean;}
interface SB extends Bet{score:number;dateScore:number;timeScore:number;weightScore:number;lengthScore:number;lookScore:number;}
const fD=(iso:string)=>{const[y,m,d]=iso.split('-');return`${d}/${m}/${y}`;};
const fT=(t:string)=>{const[h,m]=t.split(':');return`${parseInt(h,10)}:${m} hs`;};
const sDD=(b:string,r:string):number=>{const d=Math.abs(new Date(b).getTime()-new Date(r).getTime())/864e5;if(d===0)return 100;if(d<=1)return 80;if(d<=2)return 60;if(d<=3)return 40;if(d<=5)return 20;if(d<=7)return 10;return 0;};
const sTD=(b:string,r:string):number=>{const[bh,bm]=b.split(':').map(Number);const[rh,rm]=r.split(':').map(Number);const d=Math.abs((bh*60+bm)-(rh*60+rm));if(d===0)return 100;if(d<=30)return 80;if(d<=60)return 60;if(d<=120)return 40;if(d<=180)return 20;return 0;};
const sND=(b:number|null|undefined,r:number,mx:number):number=>{if(!b)return 0;const d=Math.abs(b-r);if(d===0)return 100;return Math.max(0,Math.round((1-d/mx)*100));};
const calc=(bs:Bet[],rd:RD):SB[]=>bs.map(b=>{const ds=sDD(b.date,rd.date);const ts=sTD(b.time||'00:00',rd.time);const ws=sND(b.weight,rd.weight,2);const ls=sND(b.length,rd.length,10);const lks=b.look===rd.look?100:0;return{...b,score:ds*3+ts*2+ws*1.5+ls*1.5+lks*2,dateScore:ds,timeScore:ts,weightScore:ws,lengthScore:ls,lookScore:lks};}).sort((a,b)=>b.score-a.score);

export const AdminPanel:React.FC<{refreshKey:number;onRevealChange?:()=>void}>=React.memo(({refreshKey,onRevealChange})=>{
  const{theme}=useTheme();const[auth,setAuth]=useState(false);const[pi,setPi]=useState('');const[pe,setPe]=useState('');
  const[rd,setRd]=useState<RD|null>(null);const[dt,setDt]=useState('');const[tm,setTm]=useState('');const[wt,setWt]=useState('');const[ln,setLn]=useState('');const[lk,setLk]=useState('');const[sv,setSv]=useState(false);const[sm,setSm]=useState('');
  const[rk,setRk]=useState<SB[]>([]);const[sp,setSp]=useState(false);
  const lrd=useCallback(async()=>{try{const r=await getSharedItem({tableName:AT,key:AK});if(r){const d:RD=JSON.parse(r.item.value);setRd(d);setDt(d.date);setTm(d.time);setWt(String(d.weight));setLn(String(d.length));setLk(d.look);if(d.revealed)setSp(true);}}catch{}},[]);
  const lrk=useCallback(async(d:RD)=>{try{const r=await listSharedItems({tableName:TABLE});const a:Bet[]=[];for(const i of r.items){try{a.push(JSON.parse(i.value));}catch{}}setRk(calc(a,d));}catch{}},[]);
  useEffect(()=>{if(auth)lrd();},[auth,lrd]);
  useEffect(()=>{if(rd?.revealed)lrk(rd);},[rd,lrk]);
  const login=async()=>{setPe('');try{const r=await getSharedItem({tableName:AT,key:APK});const p=r?JSON.parse(r.item.value).password:DP;if(pi===p)setAuth(true);else setPe('Contraseña incorrecta 🔐');}catch{if(pi===DP)setAuth(true);else setPe('Contraseña incorrecta 🔐');}};
  const save=async(rev:boolean)=>{setSv(true);setSm('');if(!dt||!tm||!wt||!ln||!lk){setSm('¡Completá todos los campos!');setSv(false);return;}try{const d:RD={date:dt,time:tm,weight:parseFloat(wt),length:parseFloat(ln),look:lk,revealed:rev};await putSharedItem({tableName:AT,key:AK,value:JSON.stringify(d),writeMode:'UPSERT'});setRd(d);if(rev){await lrk(d);setSp(true);setSm('🎉 ¡Resultados revelados!');}else setSm('✅ Datos guardados');onRevealChange?.();}catch(e:any){setSm(e instanceof StorageError?e.message:'Error');}finally{setSv(false);}};
  const is:React.CSSProperties={width:'100%',padding:'.6rem .75rem',borderRadius:10,border:`1.5px solid ${theme.inputBorder}`,fontSize:'1rem',outline:'none',boxSizing:'border-box',fontFamily:'inherit',background:theme.inputBg,color:theme.text};
  const md=['🥇','🥈','🥉'];const pc=theme.dark?['linear-gradient(135deg,#5a3d10,#8a6d20)','linear-gradient(135deg,#3a3a4a,#5a5a6a)','linear-gradient(135deg,#4a2a10,#6a4420)']:['linear-gradient(135deg,#fff9c4,#ffd54f)','linear-gradient(135deg,#eceff1,#cfd8dc)','linear-gradient(135deg,#ffe0b2,#ffcc80)'];
  if(!auth)return<div className="bet-card fade-slide-in" style={{background:theme.bgCard,borderRadius:18,padding:'2rem',maxWidth:400,width:'100%',margin:'0 auto',boxShadow:theme.shadow,border:`2px solid ${theme.border}`,textAlign:'center'}}><span style={{fontSize:'3rem'}}>🔐</span><h2 style={{margin:'.5rem 0',color:theme.accent}}>Panel Admin</h2><p style={{color:theme.textSub,fontSize:'.9rem',margin:'0 0 1rem'}}>Solo para los papás de Alanna 😉</p><input style={is} type="password" placeholder="Contraseña..." value={pi} onChange={e=>setPi(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()}/><button className="btn-hover" onClick={login} style={{width:'100%',padding:'.75rem',borderRadius:12,border:'none',background:'linear-gradient(135deg,#e91e90,#f06292)',color:'#fff',fontSize:'1rem',fontWeight:700,cursor:'pointer',marginTop:12}}>Entrar 🚪</button>{pe&&<p style={{color:'#d32f2f',marginTop:10,fontSize:'.9rem'}}>❌ {pe}</p>}</div>;
  return<div className="bet-card fade-slide-in" style={{background:theme.bgCard,borderRadius:18,padding:'1.5rem',width:'100%',maxWidth:1060,boxShadow:theme.shadow,border:`2px solid ${theme.border}`}}>
    <h2 style={{margin:'0 0 .5rem',fontSize:'1.4rem',color:theme.accent,textAlign:'center'}}>🏆 Panel de Revelación</h2>
    <p style={{textAlign:'center',color:theme.textSub,fontSize:'.9rem',margin:'0 0 1.25rem'}}>Cargá los datos reales del nacimiento de Alanna y revelá los ganadores</p>
    <AccessCodeManager/><DeadlineManager/><CsvExporter/>
    <div style={{background:theme.dark?theme.bgCardAlt:'#fff8fa',borderRadius:14,padding:'1.25rem',border:`1.5px dashed ${theme.accent}`,marginBottom:'1.25rem'}}>
      <h3 style={{margin:'0 0 1rem',fontSize:'1.05rem',color:theme.accent}}>🍼 Datos reales del nacimiento</h3>
      <div className="admin-grid" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><div><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.85rem'}}>📅 Fecha</label><input style={is} type="date" value={dt} onChange={e=>setDt(e.target.value)}/></div><div><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.85rem'}}>🕐 Hora</label><input style={is} type="time" value={tm} onChange={e=>setTm(e.target.value)}/></div><div><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.85rem'}}>⚖️ Peso (kg)</label><input style={is} type="number" placeholder="3.2" value={wt} onChange={e=>setWt(e.target.value)} step="0.01"/></div><div><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.85rem'}}>📏 Largo (cm)</label><input style={is} type="number" placeholder="49" value={ln} onChange={e=>setLn(e.target.value)} step="0.5"/></div></div>
      <div style={{marginTop:12}}><label style={{display:'block',marginBottom:6,fontWeight:600,color:theme.textSub,fontSize:'.85rem'}}>👶 ¿Cómo salió Alanna?</label><div style={{display:'flex',flexWrap:'wrap',gap:6}}>{LOOK_OPTIONS.map(o=><button key={o.value} className="btn-hover" onClick={()=>setLk(o.value)} style={{padding:'.4rem .7rem',borderRadius:10,cursor:'pointer',fontFamily:'inherit',border:`1.5px solid ${lk===o.value?theme.accent:theme.inputBorder}`,background:lk===o.value?(theme.dark?theme.accentLight:'#fce4ec'):theme.inputBg,color:lk===o.value?theme.accent:theme.text,fontSize:'.82rem',fontWeight:600}}>{o.emoji} {o.title}</button>)}</div></div>
      <div style={{display:'flex',gap:10,marginTop:16}}><button className="btn-hover" onClick={()=>save(false)} disabled={sv} style={{flex:1,padding:'.7rem',borderRadius:12,border:`2px solid ${theme.accent}`,background:'transparent',color:theme.accent,fontSize:'.95rem',fontWeight:700,cursor:'pointer'}}>💾 Guardar borrador</button><button className="btn-hover" onClick={()=>save(true)} disabled={sv} style={{flex:1,padding:'.7rem',borderRadius:12,border:'none',background:'linear-gradient(135deg,#e91e90,#f06292)',color:'#fff',fontSize:'.95rem',fontWeight:700,cursor:'pointer'}}>🎉 ¡Revelar ganadores!</button></div>
      {sm&&<p style={{textAlign:'center',marginTop:10,fontSize:'.9rem',fontWeight:600,color:sm.startsWith('Error')||sm.startsWith('¡Comp')?'#d32f2f':'#2e7d32'}}>{sm}</p>}
    </div>
    {sp&&rk.length>0&&<div className="pop-in"><div style={{textAlign:'center',marginBottom:'1.25rem',padding:'1rem',background:theme.dark?'linear-gradient(135deg,#3d2b10,#4a3510)':'linear-gradient(135deg,#fff9c4,#ffe082)',borderRadius:14,border:`2px dashed ${theme.dark?'#8a6d20':'#f9a825'}`}}><p style={{margin:0,fontWeight:800,fontSize:'1rem',color:theme.dark?'#ffc107':'#e65100'}}>🍼 Alanna nació el {fD(rd!.date)} a las {fT(rd!.time)}</p><p style={{margin:'4px 0 0',fontSize:'.9rem',color:theme.dark?'#ffc107':'#e65100'}}>⚖️ {rd!.weight} kg · 📏 {rd!.length} cm · {LOOK_MAP[rd!.look]?.emoji} {LOOK_MAP[rd!.look]?.title}</p></div>
    <h3 style={{textAlign:'center',color:theme.accent,fontSize:'1.3rem',margin:'0 0 1rem'}}>🏆 ¡Podio del Prode de Alanna! 🏆</h3>
    <div style={{display:'flex',justifyContent:'center',alignItems:'flex-end',gap:12,marginBottom:'1.5rem'}}>{[1,0,2].map(idx=>{const r=rk[idx];if(!r)return null;const h=[160,120,100];return<div key={r.nickname} className="pop-in" style={{textAlign:'center',animationDelay:`${idx*.15}s`}}><span style={{fontSize:idx===0?'2.5rem':'2rem'}}>{md[idx]}</span><p style={{margin:'2px 0',fontWeight:800,fontSize:idx===0?'1.1rem':'.95rem',color:theme.text}}>{r.nickname}</p><p style={{margin:0,fontSize:'.8rem',color:theme.accent,fontWeight:700}}>{Math.round(r.score)} pts</p><div style={{width:idx===0?100:80,height:h[idx],borderRadius:'10px 10px 0 0',background:pc[idx],marginTop:6,display:'flex',alignItems:'center',justifyContent:'center',border:`2px solid ${theme.border}`,borderBottom:'none'}}><span style={{fontSize:'2rem',fontWeight:900,color:theme.accent}}>{idx+1}°</span></div></div>;})}</div>
    <div style={{display:'flex',justifyContent:'center',marginBottom:'1.25rem'}}><ShareWinnerButton winner={rk[0].nickname} points={Math.round(rk[0].score)} runnerUp={rk[1]?.nickname} third={rk[2]?.nickname}/></div>
    <div className="rank-table" style={{borderRadius:12,overflow:'hidden',border:`1px solid ${theme.borderLight}`}}><div className="rank-row" style={{display:'grid',gridTemplateColumns:'50px 1fr 55px 55px 55px 55px 55px 65px',padding:'.5rem .75rem',fontWeight:700,fontSize:'.72rem',color:theme.accent,background:theme.dark?theme.bgCardAlt:'#fff5f8',textTransform:'uppercase',letterSpacing:.5}}><span>#</span><span>Jugador</span><span>📅</span><span>🕐</span><span>⚖️</span><span>📏</span><span>👶</span><span>Total</span></div>{rk.map((r,i)=><div key={r.nickname} className="rank-row" style={{display:'grid',gridTemplateColumns:'50px 1fr 55px 55px 55px 55px 55px 65px',padding:'.5rem .75rem',fontSize:'.82rem',borderTop:`1px solid ${theme.borderLight}`,background:i<3?(theme.dark?'rgba(240,98,146,.08)':'#fff0f5'):(i%2===0?theme.bgCardAlt:theme.bgCard)}}><span style={{fontWeight:700,color:i<3?theme.accent:theme.text}}>{i<3?md[i]:`${i+1}°`}</span><span style={{fontWeight:600,color:theme.text,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.nickname}</span><span style={{color:theme.textSub}}>{r.dateScore}</span><span style={{color:theme.textSub}}>{r.timeScore}</span><span style={{color:theme.textSub}}>{r.weightScore}</span><span style={{color:theme.textSub}}>{r.lengthScore}</span><span style={{color:theme.textSub}}>{r.lookScore}</span><span style={{fontWeight:800,color:theme.accent}}>{Math.round(r.score)}</span></div>)}</div>
    <p style={{textAlign:'center',color:theme.textMuted,fontSize:'.75rem',marginTop:10,marginBottom:0}}>Puntaje: Fecha (×3) + Hora (×2) + Look (×2) + Peso (×1.5) + Largo (×1.5)</p></div>}
  </div>;
});
AdminPanel.displayName='AdminPanel';

export const PublicResults:React.FC<{refreshKey:number}>=React.memo(({refreshKey})=>{
  const{theme}=useTheme();const[rd,setRd]=useState<RD|null>(null);const[rk,setRk]=useState<SB[]>([]);const[ld,setLd]=useState(true);const[cf,setCf]=useState(false);
  useEffect(()=>{(async()=>{try{const r=await getSharedItem({tableName:AT,key:AK});if(r){const d:RD=JSON.parse(r.item.value);if(d.revealed){setRd(d);const r2=await listSharedItems({tableName:TABLE});const a:Bet[]=[];for(const i of r2.items){try{a.push(JSON.parse(i.value));}catch{}}setRk(calc(a,d));try{if(!sessionStorage.getItem('prode-cf')){setCf(true);sessionStorage.setItem('prode-cf','1');}}catch{setCf(true);}}}}catch{}finally{setLd(false);}})();},[refreshKey]);
  if(ld||!rd||rk.length===0)return null;
  const md=['🥇','🥈','🥉'];const pc=theme.dark?['linear-gradient(135deg,#5a3d10,#8a6d20)','linear-gradient(135deg,#3a3a4a,#5a5a6a)','linear-gradient(135deg,#4a2a10,#6a4420)']:['linear-gradient(135deg,#fff9c4,#ffd54f)','linear-gradient(135deg,#eceff1,#cfd8dc)','linear-gradient(135deg,#ffe0b2,#ffcc80)'];
  return<>{cf&&<Confetti duration={5000} onDone={()=>setCf(false)}/>}<div className="bet-card fade-slide-in" style={{background:theme.bgCard,borderRadius:18,padding:'1.5rem',width:'100%',maxWidth:1060,boxShadow:theme.shadow,border:`2px solid ${theme.border}`}}>
    <div style={{textAlign:'center',fontSize:'2rem',marginBottom:4}}>🎉🎊👶🎊🎉</div><h2 style={{margin:'0 0 .25rem',textAlign:'center',fontSize:'1.5rem',color:theme.accent}}>¡Ya nació Alanna!</h2>
    <div style={{textAlign:'center',marginBottom:'1.25rem',padding:'1rem',background:theme.dark?'linear-gradient(135deg,#3d2b10,#4a3510)':'linear-gradient(135deg,#fff9c4,#ffe082)',borderRadius:14,border:`2px dashed ${theme.dark?'#8a6d20':'#f9a825'}`}}><p style={{margin:0,fontWeight:800,fontSize:'1rem',color:theme.dark?'#ffc107':'#e65100'}}>🍼 Nació el {fD(rd.date)} a las {fT(rd.time)}</p><p style={{margin:'4px 0 0',fontSize:'.9rem',color:theme.dark?'#ffc107':'#e65100'}}>⚖️ {rd.weight} kg · 📏 {rd.length} cm · {LOOK_MAP[rd.look]?.emoji} {LOOK_MAP[rd.look]?.title}</p></div>
    <h3 style={{textAlign:'center',color:theme.accent,fontSize:'1.3rem',margin:'0 0 1rem'}}>🏆 ¡Podio del Prode! 🏆</h3>
    <div style={{display:'flex',justifyContent:'center',alignItems:'flex-end',gap:12,marginBottom:'1.25rem'}}>{[1,0,2].map(idx=>{const r=rk[idx];if(!r)return null;const h=[160,120,100];return<div key={r.nickname} className="pop-in" style={{textAlign:'center',animationDelay:`${idx*.15}s`}}><span style={{fontSize:idx===0?'2.5rem':'2rem'}}>{md[idx]}</span><p style={{margin:'2px 0',fontWeight:800,fontSize:idx===0?'1.1rem':'.95rem',color:theme.text}}>{r.nickname}</p><p style={{margin:0,fontSize:'.8rem',color:theme.accent,fontWeight:700}}>{Math.round(r.score)} pts</p><div style={{width:idx===0?100:80,height:h[idx],borderRadius:'10px 10px 0 0',background:pc[idx],marginTop:6,display:'flex',alignItems:'center',justifyContent:'center',border:`2px solid ${theme.border}`,borderBottom:'none'}}><span style={{fontSize:'2rem',fontWeight:900,color:theme.accent}}>{idx+1}°</span></div></div>;})}</div>
    <div style={{display:'flex',justifyContent:'center',marginBottom:'1.25rem'}}><ShareWinnerButton winner={rk[0].nickname} points={Math.round(rk[0].score)} runnerUp={rk[1]?.nickname} third={rk[2]?.nickname}/></div>
    <div className="rank-table" style={{borderRadius:12,overflow:'hidden',border:`1px solid ${theme.borderLight}`}}><div className="rank-row" style={{display:'grid',gridTemplateColumns:'50px 1fr 55px 55px 55px 55px 55px 65px',padding:'.5rem .75rem',fontWeight:700,fontSize:'.72rem',color:theme.accent,background:theme.dark?theme.bgCardAlt:'#fff5f8',textTransform:'uppercase',letterSpacing:.5}}><span>#</span><span>Jugador</span><span>📅</span><span>🕐</span><span>⚖️</span><span>📏</span><span>👶</span><span>Total</span></div>{rk.slice(0,20).map((r,i)=><div key={r.nickname} className="rank-row" style={{display:'grid',gridTemplateColumns:'50px 1fr 55px 55px 55px 55px 55px 65px',padding:'.5rem .75rem',fontSize:'.82rem',borderTop:`1px solid ${theme.borderLight}`,background:i<3?(theme.dark?'rgba(240,98,146,.08)':'#fff0f5'):(i%2===0?theme.bgCardAlt:theme.bgCard)}}><span style={{fontWeight:700,color:i<3?theme.accent:theme.text}}>{i<3?md[i]:`${i+1}°`}</span><span style={{fontWeight:600,color:theme.text,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.nickname}</span><span style={{color:theme.textSub}}>{r.dateScore}</span><span style={{color:theme.textSub}}>{r.timeScore}</span><span style={{color:theme.textSub}}>{r.weightScore}</span><span style={{color:theme.textSub}}>{r.lengthScore}</span><span style={{color:theme.textSub}}>{r.lookScore}</span><span style={{fontWeight:800,color:theme.accent}}>{Math.round(r.score)}</span></div>)}</div>
    <p style={{textAlign:'center',color:theme.textMuted,fontSize:'.75rem',marginTop:10,marginBottom:0}}>Puntaje: Fecha (×3) + Hora (×2) + Look (×2) + Peso (×1.5) + Largo (×1.5)</p>
  </div></>;
});
PublicResults.displayName='PublicResults';
