import React, { useEffect, useState } from 'react';
import { putSharedItem, getSharedItem, listSharedItems, StorageError } from '../lib/storage';
import { LOOK_MAP } from './lookOptions';
import { useTheme } from './ThemeContext';
const ADMIN_TABLE='prode-admin';const DK='bet-deadline';const DD='2026-10-22';const DT='23:59';const TABLE='baby-bets';

export const DeadlineManager:React.FC=()=>{
  const{theme}=useTheme();const[dd,setDd]=useState(DD);const[dt,setDt]=useState(DT);const[sv,setSv]=useState(false);const[msg,setMsg]=useState('');
  useEffect(()=>{(async()=>{try{const r=await getSharedItem({tableName:ADMIN_TABLE,key:DK});if(r){const d=new Date(JSON.parse(r.item.value).deadline);setDd(d.toISOString().slice(0,10));setDt(d.toTimeString().slice(0,5));}}catch{}})();},[]);
  const save=async()=>{if(!dd||!dt){setMsg('❌ Completá fecha y hora');return;}setSv(true);setMsg('');try{await putSharedItem({tableName:ADMIN_TABLE,key:DK,value:JSON.stringify({deadline:`${dd}T${dt}:00`}),writeMode:'UPSERT'});const d=new Date(`${dd}T${dt}:00`);setMsg(`✅ Cierre: ${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} a las ${dt} hs`);}catch(e:any){setMsg(e instanceof StorageError?e.message:'❌ Error');}finally{setSv(false);}};
  const is:React.CSSProperties={padding:'.6rem .75rem',borderRadius:10,border:`1.5px solid ${theme.inputBorder}`,fontSize:'.95rem',outline:'none',boxSizing:'border-box',fontFamily:'inherit',background:theme.inputBg,color:theme.text,flex:1,minWidth:0};
  return<div style={{background:theme.dark?theme.bgCardAlt:'#fff8fa',borderRadius:14,padding:'1rem 1.25rem',border:`1.5px dashed ${theme.accent}`,marginBottom:'1.25rem'}}><h3 style={{margin:'0 0 .5rem',fontSize:'1rem',color:theme.accent}}>⏰ Cierre de apuestas</h3><p style={{margin:'0 0 .75rem',fontSize:'.82rem',color:theme.textSub}}>Elegí fecha y hora límite para apostar.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input style={is} type="date" value={dd} onChange={e=>setDd(e.target.value)}/><input style={{...is,maxWidth:120}} type="time" value={dt} onChange={e=>setDt(e.target.value)}/><button className="btn-hover" onClick={save} disabled={sv} style={{padding:'.6rem 1.2rem',borderRadius:10,border:'none',background:'linear-gradient(135deg,#e91e90,#f06292)',color:'#fff',fontSize:'.9rem',fontWeight:700,cursor:'pointer',whiteSpace:'nowrap'}}>{sv?'...':'💾 Guardar'}</button></div>{msg&&<p style={{marginTop:8,fontSize:'.85rem',fontWeight:600,color:msg.startsWith('✅')?'#2e7d32':'#d32f2f'}}>{msg}</p>}</div>;
};

export const CsvExporter:React.FC=()=>{
  const{theme}=useTheme();const[ex,setEx]=useState(false);const[msg,setMsg]=useState('');
  const exp=async()=>{setEx(true);setMsg('');try{const r=await listSharedItems({tableName:TABLE});const a:any[]=[];for(const i of r.items){try{a.push(JSON.parse(i.value));}catch{}}if(!a.length){setMsg('⚠️ No hay apuestas');setEx(false);return;}a.sort((x:any,y:any)=>new Date(`${x.date}T${x.time||'00:00'}`).getTime()-new Date(`${y.date}T${y.time||'00:00'}`).getTime());const esc=(s:string)=>`"${(s||'').replace(/"/g,'""')}"`;const h='Apodo,Fecha,Hora,Peso (kg),Largo (cm),Look,Mensaje';const rows=a.map((b:any)=>[esc(b.nickname),b.date,b.time||'',b.weight??'',b.length??'',esc(b.look&&LOOK_MAP[b.look]?LOOK_MAP[b.look].title:''),esc(b.message||'')].join(','));const csv='\uFEFF'+[h,...rows].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a2=document.createElement('a');a2.href=url;a2.download='apuestas-akira-eva-prode.csv';a2.click();URL.revokeObjectURL(url);setMsg(`✅ Exportadas ${a.length} apuestas`);}catch(e:any){setMsg(e?.message||'❌ Error');}finally{setEx(false);}};
  return<div style={{background:theme.dark?theme.bgCardAlt:'#fff8fa',borderRadius:14,padding:'1rem 1.25rem',border:`1.5px dashed ${theme.accent}`,marginBottom:'1.25rem'}}><h3 style={{margin:'0 0 .5rem',fontSize:'1rem',color:theme.accent}}>📋 Exportar apuestas</h3><p style={{margin:'0 0 .75rem',fontSize:'.82rem',color:theme.textSub}}>Descargá todas las apuestas en CSV.</p><button className="btn-hover" onClick={exp} disabled={ex} style={{padding:'.65rem 1.5rem',borderRadius:12,border:'none',background:'linear-gradient(135deg,#e91e90,#f06292)',color:'#fff',fontSize:'.95rem',fontWeight:700,cursor:'pointer',opacity:ex?.6:1}}>{ex?'Exportando...':'📥 Descargar CSV'}</button>{msg&&<p style={{marginTop:8,fontSize:'.85rem',fontWeight:600,color:msg.startsWith('✅')?'#2e7d32':msg.startsWith('⚠')?'#e65100':'#d32f2f'}}>{msg}</p>}</div>;
};
