import React, { useState, useEffect } from 'react';
import { putSharedItem, StorageError } from '../lib/storage';
import { BetTicket, TicketData } from './BetTicket';
import { LOOK_OPTIONS } from './lookOptions';
import { useTheme } from './ThemeContext';
import { isBettingClosed } from './deadline';
const TABLE='baby-bets';
const fmtDL=(d:Date)=>`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()} a las ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} hs`;
export const BetForm:React.FC<{onBetPlaced:()=>void}>=({onBetPlaced})=>{
  const{theme}=useTheme();const[nn,setNn]=useState('');const[dt,setDt]=useState('');const[tm,setTm]=useState('');const[wt,setWt]=useState('');const[ln,setLn]=useState('');const[lk,setLk]=useState('');const[msg,setMsg]=useState('');const[ld,setLd]=useState(false);const[err,setErr]=useState('');const[ok,setOk]=useState('');const[tk,setTk]=useState<TicketData|null>(null);const[cl,setCl]=useState(false);const[dl,setDl]=useState<Date|null>(null);
  useEffect(()=>{isBettingClosed().then(({closed:c,deadline:d})=>{setCl(c);setDl(d);});},[]);
  const submit=async()=>{setErr('');setOk('');const n=nn.trim();if(!n){setErr('¡Dale, poné un apodo!');return;}if(!dt){setErr('¡Elegí una fecha, crack!');return;}if(!tm){setErr('¡Falta la hora, metele!');return;}setLd(true);try{await putSharedItem({tableName:TABLE,key:n.toLowerCase(),value:JSON.stringify({nickname:n,date:dt,time:tm,weight:wt?parseFloat(wt):null,length:ln?parseFloat(ln):null,look:lk||null,message:msg.trim(),timestamp:Date.now()}),writeMode:'INSERT'});setOk(`¡Jugado, ${n}! Tu apuesta quedó registrada 🎲`);setTk({nickname:n,date:dt,time:tm,weight:wt?parseFloat(wt):null,length:ln?parseFloat(ln):null,look:lk||null,message:msg.trim()});setNn('');setDt('');setTm('');setWt('');setLn('');setLk('');setMsg('');onBetPlaced();}catch(e:any){if(e instanceof StorageError){setErr(e.message.includes('Conflict')||e.message.includes('already')?`¡Opa! El apodo "${n}" ya está en juego. Probá con otro.`:e.message);}else setErr('Se pudrió algo. Intentá de nuevo, pa.');}finally{setLd(false);}};
  const is:React.CSSProperties={width:'100%',padding:'.65rem .75rem',borderRadius:10,border:`1.5px solid ${theme.inputBorder}`,fontSize:'1rem',outline:'none',boxSizing:'border-box',fontFamily:'inherit',background:theme.inputBg,color:theme.text,transition:'border-color .2s,background .2s'};
  return <div className="bet-card fade-slide-in card-hover" style={{background:theme.bgCard,borderRadius:18,padding:'2rem',maxWidth:480,width:'100%',boxShadow:theme.shadow,border:`2px solid ${theme.border}`,transition:'background .3s,border-color .3s'}}>
    <h2 style={{margin:0,fontSize:'1.5rem',color:theme.accent}}>🎲 Jugá tu apuesta</h2>
    {dl&&!cl&&<p style={{margin:'.25rem 0',color:theme.textMuted,fontSize:'.78rem',textAlign:'center'}}>⏰ Las apuestas cierran el {fmtDL(dl)}</p>}
    {cl?<div style={{textAlign:'center',padding:'2rem 1rem'}}><span style={{fontSize:'3rem'}}>🔒</span><p style={{fontSize:'1.2rem',fontWeight:700,color:theme.accent,margin:'.5rem 0 .25rem'}}>¡Las apuestas están cerradas!</p><p style={{color:theme.textSub,fontSize:'.95rem',margin:0}}>Se terminó el tiempo, ¡ahora a esperar a Alanna! 🍼</p>{dl&&<p style={{color:theme.textMuted,fontSize:'.8rem',marginTop:8}}>Cerraron el {fmtDL(dl)}</p>}</div>:<>
    <p style={{margin:'.25rem 0 1.25rem',color:theme.textSub,fontSize:'.95rem'}}>¿Cuándo llega Alanna? Metele fecha y hora 👇</p>
    <div style={{marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>🏷️ Tu apodo</label><input style={is} type="text" placeholder="Ej: TíaLaura, ElPadrino..." value={nn} onChange={e=>setNn(e.target.value)} maxLength={30}/></div>
    <div style={{marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>📅 Fecha de nacimiento</label><input style={is} type="date" value={dt} onChange={e=>setDt(e.target.value)}/></div>
    <div style={{marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>🕐 Hora estimada</label><input style={is} type="time" value={tm} onChange={e=>setTm(e.target.value)}/></div>
    <div style={{textAlign:'center',margin:'.5rem 0 1rem',padding:'.6rem',background:theme.dark?theme.bgCardAlt:'#fff8fa',borderRadius:10,border:`1px dashed ${theme.accent}`}}><span style={{display:'block',fontWeight:700,color:theme.accent,fontSize:'.95rem'}}>🎰 Apuestas bonus (opcional)</span><span style={{display:'block',fontSize:'.78rem',color:theme.textMuted,marginTop:2}}>¡Más categorías, más chances de ganar!</span></div>
    <div className="form-row-2" style={{display:'flex',gap:12}}><div style={{flex:1,marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>⚖️ Peso (kg)</label><input style={is} type="number" placeholder="Ej: 3.2" value={wt} onChange={e=>setWt(e.target.value)} min="1" max="6" step="0.1"/></div><div style={{flex:1,marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>📏 Largo (cm)</label><input style={is} type="number" placeholder="Ej: 49" value={ln} onChange={e=>setLn(e.target.value)} min="30" max="60" step="0.5"/></div></div>
    <div style={{marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:6,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>👶 ¿Cómo voy a ser?</label><div className="look-grid-mobile" style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:8}}>{LOOK_OPTIONS.map(o=>{const s=lk===o.value;return<button key={o.value} type="button" className="look-card" style={{padding:'.6rem .65rem',borderRadius:12,border:`1.5px solid ${s?theme.accent:theme.inputBorder}`,background:s?(theme.dark?theme.accentLight:'linear-gradient(135deg,#fce4ec,#f8bbd0)'):theme.inputBg,cursor:'pointer',fontFamily:'inherit',textAlign:'left',boxShadow:s?(theme.dark?'0 2px 8px rgba(240,98,146,.3)':'0 2px 8px rgba(233,30,144,.2)'):'none'}} onClick={()=>setLk(s?'':o.value)}><span style={{display:'block',fontSize:'1.3rem',marginBottom:2}}>{o.emoji}</span><span style={{display:'block',fontWeight:700,fontSize:'.82rem',color:theme.accent}}>{o.title}</span><span style={{display:'block',fontSize:'.72rem',color:theme.textSub,marginTop:1,lineHeight:1.3}}>{o.desc}</span><span style={{display:'block',fontSize:'.68rem',color:theme.textMuted,fontStyle:'italic',marginTop:3,lineHeight:1.3}}>{o.quote}</span></button>;})}</div></div>
    <div style={{marginBottom:'1rem',textAlign:'left'}}><label style={{display:'block',marginBottom:4,fontWeight:600,color:theme.textSub,fontSize:'.9rem'}}>💌 Mensaje para Alanna</label><textarea style={{...is,minHeight:70,resize:'vertical'}} placeholder="Dejale unas palabras lindas a la beba..." value={msg} onChange={e=>setMsg(e.target.value)} maxLength={200}/><span style={{display:'block',textAlign:'right',fontSize:'.75rem',color:theme.textMuted,marginTop:2}}>{msg.length}/200</span></div>
    <button className="btn-hover" onClick={submit} disabled={ld} style={{width:'100%',padding:'.85rem',borderRadius:14,border:'none',background:'linear-gradient(135deg,#e91e90,#f06292)',color:'#fff',fontSize:'1.15rem',fontWeight:700,cursor:'pointer',marginTop:8,letterSpacing:.5,opacity:ld?.6:1}}>{ld?'Registrando...':'🎰 ¡Apostar ya!'}</button>
    {err&&<p style={{color:'#d32f2f',marginTop:12,fontSize:'.9rem',fontWeight:500}}>❌ {err}</p>}
    {ok&&<p className="pop-in" style={{color:'#2e7d32',marginTop:12,fontSize:'.95rem',fontWeight:600}}>{ok}</p>}
    </>}
    {tk&&<BetTicket data={tk} onClose={()=>setTk(null)}/>}
  </div>;
};
